//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audioVisuales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AudiovisualesDBEntities1 : DbContext
    {
        public AudiovisualesDBEntities1()
            : base("name=AudiovisualesDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<Modelos> Modelos { get; set; }
        public virtual DbSet<Renta_Dev> Renta_Dev { get; set; }
        public virtual DbSet<Tecnologia_Conexion> Tecnologia_Conexion { get; set; }
        public virtual DbSet<Tipos_Equipos> Tipos_Equipos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
