//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audioVisuales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipos()
        {
            this.Renta_Dev = new HashSet<Renta_Dev>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public string NSerial { get; set; }
        public string ServiceTag { get; set; }
        public Nullable<int> TipoEquipoID { get; set; }
        public Nullable<int> MarcaID { get; set; }
        public Nullable<int> ModeloID { get; set; }
        public Nullable<int> TCID { get; set; }
        public string Estado { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual Tecnologia_Conexion Tecnologia_Conexion { get; set; }
        public virtual Tipos_Equipos Tipos_Equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renta_Dev> Renta_Dev { get; set; }
    }
}
