//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace audioVisuales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renta_Dev
    {
        public int NoPrestamo { get; set; }
        public int Empleado { get; set; }
        public int Equipo { get; set; }
        public int Usuario { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
